### PR TITLE
Fix errors with build and improve it

### PR DESCRIPTION
**Pull request by grv87**
Errors:
* Missing `DB_USER` and `DB_PASSWORD` env vars
* Hikari 5.0.0 doesn't work under Java 8

Also, some improvements:
* Don't use Gradle Wrapper when we have Gradle Docker image
* Remove unused (and so confusing) Dockerfile in docker-databases

### CODE REVIEW

**Review by 1gravity — CHANGES_REQUESTED** [review]
env variables are used when starting the services as Docker containers but also when starting the services (well the one service) without docker (just starting the service main function). DB_HOST can be "postgres" in docker-compose.yaml because docker will resolve the host to the container name so connecting to "postgres" will work as long as the db runs as docker container. Without containers "postgres" is not a valid host and my .env file actually says "DB_HOST=localhost". Your solution works in the docker-compose world but my intention was to have the ability to run just locally without containers. I think the problem is only with the host name, the rest of the substitutions should work.
Also btw running tests happens locally, without containers.

**Review by 1gravity — CHANGES_REQUESTED** [review]
If I'm not mistaken the docker file is used to create the databases if they don't exist yet. It works together with the "- ./docker-databases:/docker-entrypoint-initdb.d" volume definition.

**Review by 1gravity — APPROVED** [review]

**Review by 1gravity — APPROVED** [review]

**Comment by grv87** [comment]
@1gravity, on env file - I agree, I didn't consider all use cases. My initial problem was with `DB_USER`. I think I better add `DB_USER` only and remove my other attempts to DRY. Ok?

On initdb, have you figured it out? See its README - there are 2 methods. Either build custom image with provided Dockerfile and use it or mount this dir into existing one. You don't need both.

**Comment by 1gravity** [comment]
> @1gravity, on env file - I agree, I didn't consider all use cases. My initial problem was with `DB_USER`. I think I better add `DB_USER` only and remove my other attempts to DRY. Ok?

Not sure what the problem with the `DB_USER` is. The docker-compose environment is really just a local development environment so it doesn't really matter which db user / password you're using. You can always tear it down and create it from scratch. I'd like to stick to a consistent approach for the environment variables meaning they are defined:
1. in the docker-compose file for the docker-compose environment
2. in a .env file when you run it locally without containers
3. in some environment variable definition if you deploy in a more controlled environment (testing, staging, production)
 
> On initdb, have you figured it out? See its README - there are 2 methods. Either build custom image with provided Dockerfile and use it or mount this dir into existing one. You don't need both.

Yes one or the other and I like the script approach better so the docker file is removed.

**Comment by 1gravity** [comment]
> > @1gravity, on env file - I agree, I didn't consider all use cases. My initial problem was with `DB_USER`. I think I better add `DB_USER` only and remove my other attempts to DRY. Ok?
> 
> Not sure what the problem with the `DB_USER` is. The docker-compose environment is really just a local development environment so it doesn't really matter which db user / password you're using. You can always tear it down and create it from scratch. I'd like to stick to a consistent approach for the environment variables meaning they are defined:

I can see now what the problem is. The db environment variables `DB_USER` and `DB_PASSWORD` are missing in the `docker-compose` file. I added them. I guess it worked for me before because they were defined in a .env file as well.

**Comment by grv87** [comment]
@1gravity, I think that the problem with `DB_USER` should be solved differently.

Why do you need these in tests?

https://github.com/1gravity/Ktor-Template/blob/74f490758a2c157a9704485d04df205406639bd1/account-service/src/test/kotlin/com/onegravity/accountservice/util/TestDatabaseConfigImpl.kt#L15-L16

Testcontainers already set user and password. Why do you want to change them?
It's more logical to do vice versa: while creating the test application, use the password and username provided by the test db container.

**Pull request closed without merging**
